site_name: Flood Risk Analysis Tool
site_url: https://Shun456789.github.io/Flood-Risk-Analysis-Tool/
theme:
  name: material
  palette: 
    scheme: default
    primary: blues
    accent: light-blue
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Features: features.md
  - Installation: installation.md
  - Usage: usage.md
  - API Reference: api_reference.md
  - Contributing: contributing.md
  - License: license.md

