site_name: Flood Risk Analysis Tool
site_url: https://Shun456789.github.io/Flood-Risk-Analysis-Tool/
theme:
  name: material
  palette: 
    scheme: default
    primary: blue
    accent: light-blue
nav:
  - Home: index.md
  - Code Description: codes.md
  - Inundation Rasters: usage.md
  - Code Diagram: diagram.md
  - Requirements: requirements.md
  - Function and Class Documentation: function_docs.md
  - GitHub: https://github.com/Shun456789/Flood-Risk-Analysis-Tool
